apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - serviceaccount.yaml
  - token.yaml
  - connection.yaml
  - servingruntime.yaml
  - inferenceservice.yaml
