apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-3-8b-model-storage
  namespace: demo
  labels:
    app.kubernetes.io/name: llama-3-8b
    app.kubernetes.io/part-of: rhoai-demos
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
