apiVersion: v1
kind: Secret
metadata:
  name: qwen3-vl-embedding-2b
  namespace: demo
  annotations:
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/description: ''
    openshift.io/display-name: qwen3-vl-embedding-2b
    argocd.argoproj.io/sync-wave: "14"
  labels:
    opendatahub.io/dashboard: 'true'
type: Opaque
stringData:
  URI: "pvc://qwen3-vl-embedding-2b-model-storage/Qwen3-VL-Embedding-2B"
