apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware-profile-g6e-2xlarge
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: hardware-profile-g6e-2xlarge
    app.kubernetes.io/part-of: rhoai-demos
    app.kubernetes.io/component: platform-hardware-profile
spec:
  project: default
  source:
    repoURL: https://github.com/dandawg/rhoai-model-serving.git
    targetRevision: main
    path: platform/hardware-profiles/g6e-2xlarge
  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-applications
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: infrastructure.opendatahub.io
      kind: HardwareProfile
      jsonPointers:
        - /metadata/annotations/opendatahub.io~1dashboard-feature-visibility
