apiVersion: v1
kind: Secret
metadata:
  name: default-name-qwen3-vl-4b-sa
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: qwen3-vl-4b-sa
    openshift.io/display-name: default-name
    argocd.argoproj.io/sync-wave: "14"
  labels:
    opendatahub.io/dashboard: 'true'
type: kubernetes.io/service-account-token
