apiVersion: v1
kind: Secret
metadata:
  name: qwen35-27b-gguf
  namespace: demo
  annotations:
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/description: ''
    openshift.io/display-name: qwen35-27b-gguf
    argocd.argoproj.io/sync-wave: "14"
  labels:
    opendatahub.io/dashboard: 'true'
type: Opaque
stringData:
  URI: "pvc://qwen35-27b-gguf-model-storage/Qwen3.5-27B-GGUF"
