apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  # Job-specific base (configmap, job)
  - ../base
  # PVC for this variant
  - pvc.yaml

patches:
  - target:
      kind: Job
      name: download-granite-7b
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: model-storage
          persistentVolumeClaim:
            claimName: granite-7b-model-storage
