apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: granite-7b-model-storage
  namespace: demo
  labels:
    app.kubernetes.io/name: granite-7b
    app.kubernetes.io/part-of: rhoai-demos
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # storageClassName: gp3-csi  # Uncomment and specify if needed
